name: Count Lines of Code

on: [push]

jobs:
  count_loc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Count lines of code
        run: cloc .
